import { db } from "@/db";
import { vehicles, inquiries, testimonials } from "@/db/schema";
import { count } from "drizzle-orm";

export async function ensureSeeded() {
  try {
    const existingVehiclesCount = await db.select({ value: count() }).from(vehicles);
    if (Number(existingVehiclesCount[0]?.value || 0) > 0) {
      return;
    }

    await db.insert(vehicles).values([
      {
        slug: "porsche-911-gt3-rs-weissach-2024",
        title: "2024 Porsche 911 GT3 RS Weissach Package",
        category: "Pre-Loved Luxury",
        brand: "Porsche",
        model: "911 GT3 RS",
        year: 2024,
        priceInr: "₹ 3.85 Cr",
        priceRaw: 385,
        kmsDriven: 1450,
        fuelType: "Petrol",
        transmission: "PDK Automatic",
        bodyType: "Supercar",
        seatingCapacity: 2,
        ownerHistory: "1st Owner",
        registrationCity: "MH-01 Mumbai",
        exteriorColor: "Chalk Grey with Exposed Weissach Carbon",
        interiorColor: "Alcantara & Carbon Fiber Race Bucket Seats",
        engineSpecs: "4.0L Naturally Aspirated Flat-6 (518 HP @ 9,000 RPM)",
        acceleration0to100: "3.0 sec",
        topSpeed: "296 km/h",
        imageUrl: "https://images.pexels.com/photos/30687976/pexels-photo-30687976.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/30687976/pexels-photo-30687976.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
          "https://images.pexels.com/photos/17632052/pexels-photo-17632052.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
          "https://images.pexels.com/photos/18536578/pexels-photo-18536578.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "Official Porsche India Warranty till Nov 2028",
        highlights: [
          "Weissach Package (Magnesium Wheels & Carbon Roll Cage)",
          "Front Axle Lift System with GPS Memory",
          "DRS Active Swan-Neck Carbon Rear Wing",
          "Full Body Self-Healing Xpel Stealth PPF"
        ],
        isFeatured: true,
        isHeroSlide: true,
      },
      {
        slug: "ferrari-296-gtb-assetto-fiorano-2025",
        title: "2025 Ferrari 296 GTB Assetto Fiorano",
        category: "Un-Registered Exotics",
        brand: "Ferrari",
        model: "296 GTB",
        year: 2025,
        priceInr: "₹ 5.60 Cr",
        priceRaw: 560,
        kmsDriven: 0,
        fuelType: "Hybrid",
        transmission: "8-Speed F1 DCT",
        bodyType: "Supercar",
        seatingCapacity: 2,
        ownerHistory: "Unregistered (0 KM)",
        registrationCity: "Unregistered Zero-Meter",
        exteriorColor: "Rosso Corsa with Modena Yellow Calipers",
        interiorColor: "Nero Ade Leather with Rosso Contrast Stitching",
        engineSpecs: "3.0L Twin-Turbo 120° V6 Plug-In Hybrid (819 HP)",
        acceleration0to100: "2.7 sec",
        topSpeed: "330 km/h",
        imageUrl: "https://images.pexels.com/photos/17866515/pexels-photo-17866515.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/17866515/pexels-photo-17866515.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
          "https://images.pexels.com/photos/5495045/pexels-photo-5495045.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
          "https://images.pexels.com/photos/9399193/pexels-photo-9399193.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "7-Year Genuine Ferrari Maintenance & Factory Cover",
        highlights: [
          "Assetto Fiorano Track Package with Multimatic Dampers",
          "Carbon Fibre Racing Seats (Large Size)",
          "Passenger Cockpit Telemetry Display",
          "Brand New Unregistered Zero-Meter Title"
        ],
        isFeatured: true,
        isHeroSlide: true,
      },
      {
        slug: "lamborghini-huracan-evo-spyder-2024",
        title: "2024 Lamborghini Huracán EVO Spyder AWD",
        category: "Bespoke Showroom",
        brand: "Lamborghini",
        model: "Huracán EVO Spyder",
        year: 2024,
        priceInr: "₹ 4.45 Cr",
        priceRaw: 445,
        kmsDriven: 2800,
        fuelType: "Petrol",
        transmission: "LDF 7-Speed Dual-Clutch",
        bodyType: "Convertible",
        seatingCapacity: 2,
        ownerHistory: "1st Owner",
        registrationCity: "MH-02 Mumbai",
        exteriorColor: "Verde Mantis Pearl 4-Layer Paint",
        interiorColor: "Nero Ade Alcantara with Verde Q-Citura Embroidery",
        engineSpecs: "5.2L Naturally Aspirated V10 (640 HP)",
        acceleration0to100: "3.1 sec",
        topSpeed: "325 km/h",
        imageUrl: "https://images.pexels.com/photos/30877637/pexels-photo-30877637.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/30877637/pexels-photo-30877637.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
          "https://images.pexels.com/photos/19220973/pexels-photo-19220973.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
          "https://images.pexels.com/photos/18536578/pexels-photo-18536578.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "Lamborghini Selezione CPO Warranty till 2027",
        highlights: [
          "LDVI (Lamborghini Dinamica Veicolo Integrata) All-Wheel Steering",
          "Sensonum 390W High Performance Audio",
          "Lifting System + Magneto-Rheological Suspension",
          "Capristo Titanium Valved Performance Exhaust"
        ],
        isFeatured: true,
        isHeroSlide: true,
      },
      {
        slug: "mercedes-amg-g63-grand-edition-2024",
        title: "2024 Mercedes-AMG G 63 Grand Edition (1 of 1,000)",
        category: "Pre-Loved Luxury",
        brand: "Mercedes-AMG",
        model: "G 63 AMG",
        year: 2024,
        priceInr: "₹ 4.15 Cr",
        priceRaw: 415,
        kmsDriven: 4100,
        fuelType: "Petrol",
        transmission: "AMG SPEEDSHIFT 9G-Tronic",
        bodyType: "Luxury SUV",
        seatingCapacity: 5,
        ownerHistory: "1st Owner",
        registrationCity: "DL-3C New Delhi",
        exteriorColor: "MANUFAKTUR Night Black Magno with Gold Decals",
        interiorColor: "Black Nappa Leather with Kalahari Gold Stitching",
        engineSpecs: "4.0L V8 Biturbo Handcrafted AMG Engine (577 HP)",
        acceleration0to100: "4.5 sec",
        topSpeed: "220 km/h",
        imageUrl: "https://images.pexels.com/photos/94272/sports-car-pkw-auto-vehicle-94272.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/94272/sports-car-pkw-auto-vehicle-94272.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "Mercedes-Benz India Extended Warranty till 2028",
        highlights: [
          "Limited Grand Edition — 22-inch Techgold Forged AMG Wheels",
          "Burmester 3D High-End Surround Sound",
          "Rear Seat Entertainment & AMG Carbon Trim",
          "3 Triple-Locking Differentials & Side-Pipe AMG Exhaust"
        ],
        isFeatured: true,
        isHeroSlide: false,
      },
      {
        slug: "rolls-royce-cullinan-series-2-black-badge-2024",
        title: "2024 Rolls-Royce Cullinan Series II Black Badge",
        category: "Bespoke Showroom",
        brand: "Rolls-Royce",
        model: "Cullinan Series II",
        year: 2024,
        priceInr: "₹ 9.25 Cr",
        priceRaw: 925,
        kmsDriven: 1900,
        fuelType: "Petrol",
        transmission: "8-Speed Satellite-Aided ZF",
        bodyType: "Luxury SUV",
        seatingCapacity: 4,
        ownerHistory: "1st Owner",
        registrationCity: "MH-01 Mumbai",
        exteriorColor: "Bespoke Arctic White with Hand-Painted Gold Coachline",
        interiorColor: "Grace White & Forge Yellow Leather with Starlight Headliner",
        engineSpecs: "6.75L Twin-Turbo V12 (592 HP / 900 Nm Torque)",
        acceleration0to100: "4.9 sec",
        topSpeed: "250 km/h",
        imageUrl: "https://images.pexels.com/photos/17632052/pexels-photo-17632052.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/17632052/pexels-photo-17632052.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "Rolls-Royce Provenance Official Warranty till 2029",
        highlights: [
          "Shooting Star Fiber-Optic Illuminated Headliner",
          "Immersive Individual Rear Seating with Champagne Cooler",
          "Bespoke Audio 18-Speaker Studio System",
          "Viewing Suite Automated Rear Tailgate Seats"
        ],
        isFeatured: true,
        isHeroSlide: false,
      },
      {
        slug: "bmw-m8-competition-gran-coupe-2024",
        title: "2024 BMW M8 Competition Gran Coupe M xDrive",
        category: "Pre-Loved Luxury",
        brand: "BMW M",
        model: "M8 Competition",
        year: 2024,
        priceInr: "₹ 2.35 Cr",
        priceRaw: 235,
        kmsDriven: 5200,
        fuelType: "Petrol",
        transmission: "8-Speed M Steptronic",
        bodyType: "Coupe",
        seatingCapacity: 4,
        ownerHistory: "1st Owner",
        registrationCity: "MH-12 Pune",
        exteriorColor: "BMW Individual Dravit Grey Metallic",
        interiorColor: "Taruma Brown Full Merino Leather",
        engineSpecs: "4.4L TwinPower Turbo V8 (617 HP)",
        acceleration0to100: "3.2 sec",
        topSpeed: "305 km/h",
        imageUrl: "https://images.pexels.com/photos/17792976/pexels-photo-17792976.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/17792976/pexels-photo-17792976.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "BMW BSI Plus Maintenance Pack till 2028",
        highlights: [
          "M Carbon Ceramic Brakes with Gold Calipers",
          "Bowers & Wilkins Diamond Surround Sound (1,400W)",
          "Switchable 2WD Drift Mode & Active M Differential",
          "Laserlight Headlights with Yellow DRL Icon Signature"
        ],
        isFeatured: false,
        isHeroSlide: false,
      },
      {
        slug: "range-rover-sv-autobiography-lwb-2023",
        title: "2023 Range Rover SV Autobiography LWB 4.4 V8",
        category: "Pre-Loved Luxury",
        brand: "Range Rover",
        model: "SV Autobiography",
        year: 2023,
        priceInr: "₹ 4.60 Cr",
        priceRaw: 460,
        kmsDriven: 6800,
        fuelType: "Petrol",
        transmission: "8-Speed Automatic",
        bodyType: "Luxury SUV",
        seatingCapacity: 4,
        ownerHistory: "1st Owner",
        registrationCity: "MH-01 Mumbai",
        exteriorColor: "SV Bespoke British Racing Green Gloss",
        interiorColor: "Caraway Near-Aniline Leather with White Ceramic Controls",
        engineSpecs: "4.4L Twin-Turbo BMW-sourced V8 (523 HP)",
        acceleration0to100: "4.6 sec",
        topSpeed: "250 km/h",
        imageUrl: "https://images.pexels.com/photos/35849576/pexels-photo-35849576.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/35849576/pexels-photo-35849576.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "Land Rover Official Warranty & Service Plan",
        highlights: [
          "SV Signature Suite Club Table & Electrically Deployable Console",
          "Meridian Signature 34-Speaker 1,600W Sound",
          "Hot Stone Massage Executive Rear Recliners",
          "All-Wheel Steering & Electronic Air Suspension with Dynamic Response"
        ],
        isFeatured: false,
        isHeroSlide: false,
      },
      {
        slug: "bentley-continental-gt-speed-w12-2024",
        title: "2024 Bentley Continental GT Speed W12 Mulliner",
        category: "Un-Registered Exotics",
        brand: "Bentley",
        model: "Continental GT Speed",
        year: 2024,
        priceInr: "₹ 5.10 Cr",
        priceRaw: 510,
        kmsDriven: 0,
        fuelType: "Petrol",
        transmission: "8-Speed Dual-Clutch",
        bodyType: "Grand Tourer",
        seatingCapacity: 4,
        ownerHistory: "Unregistered (0 KM)",
        registrationCity: "Unregistered Zero-Meter",
        exteriorColor: "Beluga Black Solid with Carbon Styling Spec",
        interiorColor: "Hotspur Red & Beluga Diamond-Quilted Hide",
        engineSpecs: "6.0L Twin-Turbo Handbuilt W12 (650 HP / 900 Nm)",
        acceleration0to100: "3.5 sec",
        topSpeed: "335 km/h",
        imageUrl: "https://images.pexels.com/photos/38234790/pexels-photo-38234790.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/38234790/pexels-photo-38234790.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "Bentley Factory 3-Year Unlimited Mileage Warranty",
        highlights: [
          "Bentley Rotating Display (3-Sided Dash Wood/Analogue/Screen)",
          "Naim for Bentley 2,200W 18-Speaker Concert Audio",
          "Electronic Limited-Slip Differential (eLSD) & Carbon Ceramic Brakes",
          "Zero-Meter Import Ready for Instant Choice Registration"
        ],
        isFeatured: true,
        isHeroSlide: false,
      },
      {
        slug: "mclaren-750s-spider-2024",
        title: "2024 McLaren 750S Spider Performance Carbon",
        category: "Un-Registered Exotics",
        brand: "McLaren",
        model: "750S Spider",
        year: 2024,
        priceInr: "₹ 5.95 Cr",
        priceRaw: 595,
        kmsDriven: 850,
        fuelType: "Petrol",
        transmission: "7-Speed SSG Dual-Clutch",
        bodyType: "Convertible",
        seatingCapacity: 2,
        ownerHistory: "1st Owner",
        registrationCity: "KA-01 Bengaluru",
        exteriorColor: "McLaren Orange with Gloss Carbon Pack III",
        interiorColor: "Jet Black Alcantara & McLaren Orange P2 Performance Spec",
        engineSpecs: "4.0L Twin-Turbo M840T V8 (750 PS / 740 HP)",
        acceleration0to100: "2.8 sec",
        topSpeed: "332 km/h",
        imageUrl: "https://images.pexels.com/photos/9399193/pexels-photo-9399193.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400",
        galleryImages: [
          "https://images.pexels.com/photos/9399193/pexels-photo-9399193.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=750&w=1400"
        ],
        inspectionPoints: 150,
        certifiedStatus: true,
        warrantyStatus: "McLaren Extended Warranty till 2028",
        highlights: [
          "Retractable Electrochromic Hardtop Roof (11 seconds)",
          "Proactive Chassis Control III Hydraulic Suspension",
          "Super-Lightweight Senna Carbon Bucket Seats",
          "Bowers & Wilkins 12-Speaker High-Power System"
        ],
        isFeatured: false,
        isHeroSlide: false,
      }
    ]);

    // Authentic Google-Verified Testimonials from Wish Wheels
    await db.insert(testimonials).values([
      {
        name: "Abhishek Gupta",
        vehiclePurchased: "2023 Porsche 911 Carrera S",
        rating: 5,
        comment:
          "I run out of words when I am writing about my experience dealing with Wish Wheels team. Special mention of Raaghib whose professionalism and transparency is par excellence. Thoroughly enjoyed the whole buying experience and handholding through the regulatory process. Would recommend Wish Wheels without an iota of doubt.",
        verifiedBy: "Verified by Google",
        date: "2 weeks ago",
        avatarInitials: "AG",
      },
      {
        name: "Ankita Singh",
        vehiclePurchased: "2024 Mercedes-Benz GLE 450d",
        rating: 5,
        comment:
          "The purchase experience was seamless and efficient, demonstrating a commitment to customer satisfaction. The vehicle’s condition upon delivery was impeccable, reflecting meticulous attention to detail. Furthermore, Wish Wheels’ communication throughout the process was clear, consistent, and professional. Thanks Raaghib and Team!",
        verifiedBy: "Verified by Google",
        date: "1 month ago",
        avatarInitials: "AS",
      },
      {
        name: "Kewal Sethi",
        vehiclePurchased: "2023 Range Rover Sport Dynamic",
        rating: 5,
        comment:
          "I contacted you on Sunday afternoon & by Friday evening within 5 days my dream machine was in my hands! Thank you so much Neha & Raaghib Khan. I was a little nervous about buying a pre-owned luxury car, but after meeting you & your team the comfort & confidence I felt were truly unexplainable.",
        verifiedBy: "Verified by Google",
        date: "3 weeks ago",
        avatarInitials: "KS",
      },
      {
        name: "Prashant Pednekar",
        vehiclePurchased: "2024 BMW M8 Competition",
        rating: 5,
        comment:
          "Wish Wheels is a brand you can blindly trust. I have purchased couple of cars from them, and each experience was far beyond my expectations and kept raising the bar. They truly deliver on what they commit. I would always recommend Raaghib and his team for anyone looking for super premium quality cars.",
        verifiedBy: "Verified by Google",
        date: "2 months ago",
        avatarInitials: "PP",
      },
      {
        name: "Brijesh Tanwani",
        vehiclePurchased: "2024 Mercedes-AMG GLE 53 Coupe",
        rating: 5,
        comment:
          "My dream came true after buying from Wish Wheels. I had searched almost whole Mumbai and Pune, but the car which they offered me was as good as brand new. From booking till delivery, all commitments were fulfilled. RTO transfer and insurance transfer were done within a week. After sales service was also awesome!",
        verifiedBy: "Verified by Google",
        date: "1 month ago",
        avatarInitials: "BT",
      },
    ]);

    // Sample inquiries
    await db.insert(inquiries).values([
      {
        type: "29-Minute Car Valuation",
        customerName: "Vikram Singhania",
        phone: "+91 98201 44512",
        email: "vikram.s@singhaniacapital.in",
        city: "Mumbai (Worli)",
        carToSellBrand: "Porsche",
        carToSellModel: "Cayenne Coupe Turbo GT",
        carToSellYear: 2023,
        estimatedValuation: "₹ 2.45 Cr – ₹ 2.62 Cr",
        notes: "Looking to trade-in for the 2024 Porsche 911 GT3 RS Weissach.",
        status: "Concierge Assigned",
      },
      {
        type: "VIP Showroom Viewing",
        vehicleTitle: "2025 Ferrari 296 GTB Assetto Fiorano",
        customerName: "Aarav Oberoi",
        phone: "+91 99200 81190",
        email: "aarav@oberoigroup.co",
        preferredDate: "2026-04-05",
        city: "Mumbai (Bandra West)",
        notes: "Requesting private salon viewing at 4 PM with champagne tasting.",
        status: "Showroom Scheduled",
      }
    ]);
  } catch (err) {
    console.error("Seed warning:", err);
  }
}
